#!/usr/bin/env node
/**
 * Build the shipped clip catalog and the derived study artifacts.
 *
 *   node pipelines/motion/build.ts          # rebuild generated source and studies
 *   node pipelines/motion/build.ts --check  # verify generated source; still rebuild studies
 *   node pipelines/motion/build.ts --json   # machine-readable summary
 *
 * Studies always go to `out/`, including during a check. They are deterministic working
 * material, not tracked source, and a Blender project may already be pointed at that directory.
 */

import { existsSync, mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { dirname, join, relative, resolve } from "node:path";
import { fileURLToPath } from "node:url";

import { AUTHORED_DIR, AUTHORED_OUTPUT, buildCatalog } from "./catalog.ts";

const ROOT = resolve(dirname(fileURLToPath(import.meta.url)), "../..");

function bandaiNamcoSource(catalog: ReturnType<typeof buildCatalog>): string {
  const manifest = catalog.manifest;
  return `/*
 * Generated by pipelines/motion/build.ts. Do not edit by hand.
 *
 * Adapted from Bandai-Namco-Research-Motiondataset-1 at revision ${manifest.sourceRevision}.
 * Source data: ${manifest.sourceUrl}
 * Licence and attribution: see LICENSE.md.
 * Changes: selected, trimmed, projected to 2D, retargeted to SVGLab's eleven-bone rig,
 * resampled to 60 Hz, and reduced to sparse linear keyframes.
 */
import type { Clip } from "../types.ts";

export const BANDAI_NAMCO_CLIPS = ${JSON.stringify(catalog.bandaiNamco)} as const satisfies Record<string, Clip>;
`;
}

function authoredSource(catalog: ReturnType<typeof buildCatalog>): string {
  const derived = Object.entries(catalog.origins).filter(([, from]) => from !== null);
  return `/*
 * Generated by pipelines/motion/build.ts from ${AUTHORED_DIR}. Do not edit by hand.
 *
 * Provenance and licence: see LICENSE.md. bnr* entries are Bandai Namco adaptations;
 * lab* entries are SVGLab originals.${derived.length === 0 ? "" : `
 *
 * Adaptations in this file: ${derived.map(([key, from]) => `${key} (from ${from})`).join(", ")}.`}
 */
import type { Clip } from "../types.ts";

export const AUTHORED_CLIPS = ${JSON.stringify(catalog.authored)} as const satisfies Record<string, Clip>;

/** Which manifest clip each authored clip was tweaked from, or null when authored from scratch. */
export const AUTHORED_ORIGINS = ${JSON.stringify(catalog.origins)} as const satisfies Record<string, string | null>;
`;
}

export interface StudyArtifact {
  readonly generatedBy: "pipelines/motion/build.ts";
  readonly clip: ReturnType<typeof buildCatalog>["studies"][string];
}

function studySource(clip: ReturnType<typeof buildCatalog>["studies"][string]): string {
  const artifact: StudyArtifact = { generatedBy: "pipelines/motion/build.ts", clip };
  return `${JSON.stringify(artifact)}\n`;
}

export function writeMotionCatalog(catalog: ReturnType<typeof buildCatalog>, root = ROOT, writeGenerated = true): {
  readonly outputs: readonly string[];
  readonly studyFiles: readonly string[];
} {
  const outputs: ReadonlyArray<readonly [string, string]> = [
    [catalog.manifest.output, bandaiNamcoSource(catalog)],
    [AUTHORED_OUTPUT, authoredSource(catalog)],
  ];
  for (const [relativePath, contents] of writeGenerated ? outputs : []) {
    const path = join(root, relativePath);
    mkdirSync(dirname(path), { recursive: true });
    if (!existsSync(path) || readFileSync(path, "utf8") !== contents) writeFileSync(path, contents);
  }
  const studyFiles: string[] = [];
  for (const [key, clip] of Object.entries(catalog.studies)) {
    const path = join(root, "out", `${key}.json`);
    const contents = studySource(clip);
    mkdirSync(dirname(path), { recursive: true });
    if (!existsSync(path) || readFileSync(path, "utf8") !== contents) writeFileSync(path, contents);
    studyFiles.push(relative(root, path));
  }
  return { outputs: outputs.map(([path]) => path), studyFiles };
}

export function main(argv: readonly string[]): number {
  const check = argv.includes("--check");
  const asJson = argv.includes("--json");
  try {
    const catalog = buildCatalog(ROOT);
    const outputs: ReadonlyArray<readonly [string, string]> = [
      [catalog.manifest.output, bandaiNamcoSource(catalog)],
      [AUTHORED_OUTPUT, authoredSource(catalog)],
    ];
    const stale: string[] = [];
    for (const [relativePath, contents] of outputs) {
      const path = join(ROOT, relativePath);
      if (check) {
        if (!existsSync(path) || readFileSync(path, "utf8") !== contents) stale.push(relativePath);
      }
    }
    const written = writeMotionCatalog(catalog, ROOT, !check);
    const studyFiles = [...written.studyFiles];

    const report = {
      ok: stale.length === 0,
      checked: check,
      shipped: Object.keys(catalog.bandaiNamco).length,
      authored: Object.keys(catalog.authored).length,
      studies: Object.keys(catalog.studies).length,
      catalogBytes: Buffer.byteLength(outputs[0][1]),
      outputs: outputs.map(([path]) => path),
      studyFiles,
      stale,
    };
    if (asJson) console.log(JSON.stringify(report, null, 2));
    else if (stale.length > 0) {
      for (const path of stale) console.error(`${path} is stale — run npm run build:motions`);
    } else {
      console.log(`${check ? "checked" : "built"} ${report.shipped} shipped, ${report.authored} authored, `
        + `${report.studies} study clips; catalog ${report.catalogBytes} bytes`);
    }
    return stale.length > 0 ? 1 : 0;
  } catch (error) {
    if (asJson) console.log(JSON.stringify({ ok: false, error: (error as Error).message }, null, 2));
    else console.error(`build:motions: ${(error as Error).message}`);
    return 2;
  }
}

if (process.argv[1] && resolve(process.argv[1]) === fileURLToPath(import.meta.url)) {
  process.exit(main(process.argv.slice(2)));
}
