#!/usr/bin/env node
/**
 * Bake Boneyard's clip catalog into typed source the shell can name at compile time.
 *
 *   node pipelines/motion/generate.ts          # rebuild src/clips/generated/
 *   node pipelines/motion/generate.ts --check  # fail when the generated source is stale
 *   node pipelines/motion/generate.ts --json   # machine-readable summary
 *
 * Boneyard owns the clips; this owns whether the lab holds them as fetched data or as literals
 * a type can be taken from. It holds them as literals because a move naming a clip that does
 * not exist should fail `tsc`, not the browser — `frame-data.test.ts` asserts exactly that, and
 * `movesets.ts` needs authored clip keys before anything has been fetched.
 *
 * The lane split is the catalog's, not this file's. A clip is shipped or authored because
 * Boneyard said so.
 */

import { existsSync, mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { dirname, join, relative, resolve } from "node:path";
import { fileURLToPath } from "node:url";

import { catalogPath } from "boneyard/paths";
import type { Clip } from "boneyard";

const ROOT = resolve(dirname(fileURLToPath(import.meta.url)), "../..");
const SHIPPED_OUTPUT = join("src", "clips", "generated", "bandai-namco.ts");
const AUTHORED_OUTPUT = join("src", "clips", "generated", "authored.ts");

interface Catalog {
  readonly contract: 1;
  readonly note: string;
  readonly clips: Readonly<Record<string, Clip>>;
  readonly origins: Readonly<Record<string, string | null>>;
  readonly lanes: Readonly<Record<string, "shipped" | "authored">>;
}

export function readCatalog(path = catalogPath()): Catalog {
  const catalog = JSON.parse(readFileSync(path, "utf8")) as Catalog;
  if (catalog.contract !== 1) throw new Error(`boneyard catalog is contract ${catalog.contract}; this build understands 1`);
  if (!catalog.clips || !catalog.lanes) throw new Error("boneyard catalog has an unsupported shape");
  return catalog;
}

function lane(catalog: Catalog, wanted: "shipped" | "authored"): Readonly<Record<string, Clip>> {
  return Object.fromEntries(Object.entries(catalog.clips).filter(([key]) => catalog.lanes[key] === wanted));
}

export function generatedSources(catalog: Catalog): Readonly<Record<string, string>> {
  const authored = lane(catalog, "authored");
  const origins = Object.fromEntries(Object.keys(authored).map((key) => [key, catalog.origins[key] ?? null]));
  const preamble = (what: string): string => `/*
 * Generated by pipelines/motion/generate.ts from boneyard/catalog/clips.json. Do not edit by hand.
 *
 * ${what}
 * Provenance and licence: see boneyard/LICENSE.md.
 */
import type { Clip } from "boneyard";
`;
  return {
    [SHIPPED_OUTPUT]: `${preamble("The catalog's shipped lane: clips derived from pinned motion capture.")}
export const BANDAI_NAMCO_CLIPS = ${JSON.stringify(lane(catalog, "shipped"))} as const satisfies Record<string, Clip>;
`,
    [AUTHORED_OUTPUT]: `${preamble("The catalog's authored lane: hand-shaped clips, which win when they carry a derived clip's key.")}
export const AUTHORED_CLIPS = ${JSON.stringify(authored)} as const satisfies Record<string, Clip>;

/** Which derived clip each authored clip was tweaked from, or null when authored from scratch. */
export const AUTHORED_ORIGINS = ${JSON.stringify(origins)} as const satisfies Record<string, string | null>;
`,
  };
}

export function writeGenerated(check = false): readonly { path: string; changed: boolean; bytes: number }[] {
  return Object.entries(generatedSources(readCatalog())).map(([reference, contents]) => {
    const path = join(ROOT, reference);
    const previous = existsSync(path) ? readFileSync(path, "utf8") : "";
    if (!check && previous !== contents) {
      mkdirSync(dirname(path), { recursive: true });
      writeFileSync(path, contents);
    }
    return { path: reference, changed: previous !== contents, bytes: Buffer.byteLength(contents) };
  });
}

export function main(argv: readonly string[]): number {
  const asJson = argv.includes("--json");
  const check = argv.includes("--check");
  const unknown = argv.filter((argument) => argument !== "--json" && argument !== "--check");
  try {
    if (unknown.length > 0) throw new Error(`unknown option ${unknown[0]}`);
    const outputs = writeGenerated(check);
    const stale = outputs.filter((output) => output.changed);
    const ok = !check || stale.length === 0;
    const report = {
      ok,
      checked: check,
      source: relative(ROOT, catalogPath()),
      outputs,
      stale: stale.map((output) => output.path),
      ...(ok ? {} : { fix: "run npm run build:motions" }),
    };
    if (asJson) console.log(JSON.stringify(report, null, 2));
    else if (!ok) {
      for (const output of stale) console.error(`${output.path} is stale — run npm run build:motions`);
    } else {
      console.log(`${check ? "checked" : "generated"} ${outputs.length} clip modules; `
        + `${outputs.reduce((sum, output) => sum + output.bytes, 0)} bytes from boneyard/catalog/clips.json`);
    }
    return ok ? 0 : 1;
  } catch (error) {
    const message = (error as Error).message;
    if (asJson) console.log(JSON.stringify({ ok: false, error: message }, null, 2));
    else console.error(`build:motions: ${message}`);
    return 2;
  }
}

if (process.argv[1] && resolve(process.argv[1]) === fileURLToPath(import.meta.url)) {
  process.exit(main(process.argv.slice(2)));
}
