#!/usr/bin/env node
/** Export the playable catalog and study lane for review in Blender. */

import { execFileSync } from "node:child_process";
import { copyFileSync, existsSync, mkdirSync, readFileSync, readdirSync, writeFileSync } from "node:fs";
import { basename, dirname, isAbsolute, join, relative, resolve, sep } from "node:path";
import { fileURLToPath } from "node:url";

import type { Clip } from "../../src/clips/types.ts";
import type { FigureManifest } from "../../src/render/manifest.ts";
import type { Rig } from "../../src/rig/types.ts";
import { buildCatalog } from "../motion/catalog.ts";
import { validateAuthoredFigure } from "../render/manifest.ts";
import { findBlender } from "../dev/find-blender.ts";
import { boneArtSvg } from "./art.ts";
import { clipToBvh } from "./bvh-write.ts";

const ROOT = resolve(dirname(fileURLToPath(import.meta.url)), "../..");
const DEFAULT_OUT = join("out", "blender");
const VALUE_FLAGS = new Set(["out", "figure"]);
const BOOLEAN_FLAGS = new Set(["json", "blend"]);

interface Arguments {
  readonly clips: readonly string[];
  readonly out: string;
  readonly figure: string | null;
  readonly json: boolean;
  readonly blend: boolean;
}

function parseArguments(argv: readonly string[]): Arguments {
  const values = new Map<string, string>();
  const booleans = new Set<string>();
  const clips: string[] = [];
  for (let index = 0; index < argv.length; index += 1) {
    const token = argv[index];
    if (!token.startsWith("--")) {
      clips.push(token);
      continue;
    }
    const name = token.slice(2);
    if (VALUE_FLAGS.has(name)) {
      const value = argv[++index];
      if (!value || value.startsWith("--")) throw new Error(`--${name} needs a value`);
      values.set(name, value);
    } else if (BOOLEAN_FLAGS.has(name)) {
      booleans.add(name);
    } else {
      throw new Error(`unknown option --${name}`);
    }
  }
  return {
    clips,
    out: values.get("out") ?? DEFAULT_OUT,
    figure: values.get("figure") ?? null,
    json: booleans.has("json"),
    blend: booleans.has("blend"),
  };
}

function portable(path: string): string {
  return relative(ROOT, path).split(sep).join("/");
}

function figurePath(requested: string | null): string {
  if (requested) {
    const candidate = requested.endsWith(".json") || requested.includes("/") || requested.includes("\\")
      ? requested
      : join("figures", `${requested}.json`);
    return isAbsolute(candidate) ? candidate : resolve(ROOT, candidate);
  }
  const first = readdirSync(join(ROOT, "figures")).filter((name) => name.endsWith(".json")).sort()[0];
  if (!first) throw new Error("no figure manifests exist in figures/");
  return join(ROOT, "figures", first);
}

export function readFigure(requested: string | null, rig: Rig): { id: string; path: string; manifest: FigureManifest } {
  const path = figurePath(requested);
  if (!existsSync(path)) throw new Error(`figure manifest '${portable(path)}' does not exist`);
  const manifest = validateAuthoredFigure(JSON.parse(readFileSync(path, "utf8")) as unknown, portable(path), rig);
  for (const bone of rig.bones) {
    const reference = manifest.parts[bone.slot];
    const partPath = resolve(ROOT, reference);
    if (!partPath.startsWith(`${ROOT}${sep}`) || !existsSync(partPath)) {
      throw new Error(`${portable(path)} cannot read '${reference}' for ${bone.name}`);
    }
  }
  return { id: basename(path, ".json"), path, manifest };
}

function readme(figure: string): string {
  return `# SVGLab clips for review

Generated by \`npm run export:motions\` for figure \`${figure}\`. One BVH per playable or study
clip is baked at one frame per 60 Hz tick so it plays exactly what the lab plays. Each bone's
artwork and the measured-calibration setup script sit beside the clips.

## Opening a clip with the figure attached

\`\`\`bash
/Applications/Blender.app/Contents/MacOS/Blender --python setup.py -- bnrSwordCutNormal
\`\`\`

Or run \`npm run blender -- bnrSwordCutNormal --figure ${figure}\` to generate a reviewable
\`.blend\` file directly. With no clip name, that command builds one for every exported clip.

The script builds the eleven-bone armature itself, attaches the selected figure's art, sets the
scene to 60 FPS and points the view at the rig's plane. It never gives the skeleton to Blender's
BVH importer, and it places SVGs by reading back the magenta calibration corner rather than
assuming the importer's scale or axes.

## Sending changes back

Export the edited action as BVH at 60 FPS, then run:

\`\`\`bash
npm run import:motions -- <file.bvh> --key <clipKey>
\`\`\`

That writes \`motions/authored/<clipKey>.json\` and reports out-of-plane rotation, depth
translation and horizontal root travel that the 2D rig cannot keep. Nothing in this directory
is tracked, and reset must never clear it because a \`.blend\` may be under active editing.
`;
}

export function main(argv: readonly string[]): number {
  const args = parseArguments(argv);
  try {
    const catalog = buildCatalog(ROOT);
    const figure = readFigure(args.figure, catalog.rig);
    const available: Record<string, Clip> = { ...catalog.clips, ...catalog.studies };
    const keys = args.clips.length > 0 ? [...args.clips] : Object.keys(available);
    for (const key of keys) if (!available[key]) throw new Error(`unknown clip '${key}'`);

    const outDirectory = isAbsolute(args.out) ? args.out : resolve(ROOT, args.out);
    mkdirSync(outDirectory, { recursive: true });
    const clips = keys.map((key) => {
      const clip = available[key];
      const path = join(outDirectory, `${key}.bvh`);
      writeFileSync(path, clipToBvh(clip, catalog.rig));
      const lane = key in catalog.studies ? "study" : key in catalog.authored ? "authored" : "shipped";
      return { key, lane, frames: clip.duration + 1, keyframes: clip.keyframes.length, path: portable(path) };
    });

    const artDirectory = join(outDirectory, "art");
    mkdirSync(artDirectory, { recursive: true });
    let order = 0;
    let pathCount = 0;
    for (const boneName of catalog.rig.contract.paintOrder) {
      const bone = catalog.rig.byName.get(boneName)!;
      const source = readFileSync(resolve(ROOT, figure.manifest.parts[bone.slot]), "utf8");
      const art = boneArtSvg(bone.name, source, order);
      order = art.nextOrder;
      pathCount += art.paths;
      writeFileSync(join(artDirectory, `${bone.name}.svg`), art.svg);
    }
    copyFileSync(join(ROOT, "pipelines", "blender", "setup.py"), join(outDirectory, "setup.py"));
    writeFileSync(join(outDirectory, "README.md"), readme(figure.id));

    const blendFiles: string[] = [];
    if (args.blend) {
      const found = findBlender();
      if (!found.executable) throw new Error(`Blender was not found; looked at:\n${found.looked.map((path) => `- ${path}`).join("\n")}`);
      for (const key of keys) {
        const target = join(outDirectory, `${key}.blend`);
        execFileSync(found.executable, [
          "--factory-startup", "--background", "--python", join(outDirectory, "setup.py"),
          "--", key, "--save", target, "--quiet",
        ], { cwd: outDirectory, stdio: "pipe" });
        blendFiles.push(portable(target));
      }
    }

    const report = {
      ok: true,
      figure: figure.id,
      defaultedFigure: args.figure === null,
      out: portable(outDirectory),
      clips,
      art: { bones: catalog.rig.bones.length, paths: pathCount },
      blendFiles,
    };
    if (args.json) console.log(JSON.stringify(report, null, 2));
    else {
      console.log(`figure: ${figure.id}${args.figure === null ? " (default)" : ""}`);
      for (const clip of clips) {
        console.log(`${clip.key}.bvh  ${clip.frames} frames @ ${catalog.rig.contract.exchange.bvh.frameRate} FPS  ${clip.keyframes} keyframes  (${clip.lane})`);
      }
      console.log(`exported ${clips.length} clips and ${catalog.rig.bones.length} bone art files (${pathCount} paths) -> ${report.out}`);
      for (const path of blendFiles) console.log(`saved ${path}`);
    }
    return 0;
  } catch (error) {
    const message = (error as Error).message;
    if (args.json) console.log(JSON.stringify({ ok: false, error: message }, null, 2));
    else console.error(`export:motions: ${message}`);
    return 2;
  }
}

if (process.argv[1] && resolve(process.argv[1]) === fileURLToPath(import.meta.url)) {
  process.exit(main(process.argv.slice(2)));
}
