import { readFileSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

import { AUTHORED_DIR, AUTHORED_OUTPUT, buildCatalog } from "./motion/catalog.mjs";

const root = dirname(dirname(fileURLToPath(import.meta.url)));
const catalog = buildCatalog(root);
const manifest = catalog.manifest;
const check = process.argv.includes("--check");

const bandaiNamco = `/*
 * Generated by scripts/build-motions.mjs. Do not edit by hand.
 *
 * Adapted from Bandai-Namco-Research-Motiondataset-1 at revision ${manifest.sourceRevision}.
 * Source data: ${manifest.sourceUrl}
 * License: CC BY-NC 4.0; see third_party/bandai-namco-motiondataset-1/LICENSE and NOTICE.md.
 * Changes: selected, trimmed, projected to 2D, retargeted to SVGLab's eleven-bone rig,
 * resampled to 60 Hz, and reduced to sparse linear keyframes.
 */
import type { AnimationClip } from "../types";

export const BANDAI_NAMCO_CLIPS = ${JSON.stringify(catalog.bandaiNamco, null, 2)} as const satisfies Record<string, AnimationClip>;
`;

const derived = Object.entries(catalog.origins).filter(([, from]) => from !== null);
const authored = `/*
 * Generated by scripts/build-motions.mjs from ${AUTHORED_DIR}. Do not edit by hand.
 *
 * These clips came back from an external tool through scripts/import-motions.mjs and are
 * authored source rather than output of the Bandai Namco retarget. Each records where it came
 * from: a bnr* clip is still an adaptation of Bandai Namco material under CC BY-NC 4.0, and a
 * lab* clip was authored here on SVGLab's rig and claims no other origin.${derived.length === 0 ? "" : `
 *
 * Adaptations in this file: ${derived.map(([key, from]) => `${key} (from ${from})`).join(", ")}.`}
 */
import type { AnimationClip } from "../types";

export const AUTHORED_CLIPS = ${JSON.stringify(catalog.authored, null, 2)} as const satisfies Record<string, AnimationClip>;

/** Which manifest clip each authored clip was tweaked from, or null when authored from scratch. */
export const AUTHORED_ORIGINS = ${JSON.stringify(catalog.origins, null, 2)} as const satisfies Record<string, string | null>;
`;

const outputs = [[manifest.output, bandaiNamco], [AUTHORED_OUTPUT, authored]];
for (const [relativePath, contents] of outputs) {
  const path = join(root, relativePath);
  if (check) {
    if (readFileSync(path, "utf8") !== contents) throw new Error(`${relativePath} is stale; run npm run build:motions`);
  } else {
    writeFileSync(path, contents);
  }
}

if (!check) {
  const counts = `${Object.keys(catalog.bandaiNamco).length} manifest`
    + `${Object.keys(catalog.authored).length > 0 ? ` and ${Object.keys(catalog.authored).length} authored` : ""}`;
  console.log(`built ${counts} motion clips -> ${manifest.output}, ${AUTHORED_OUTPUT}`);
}
