import { readFileSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

import { parseBvh } from "./motion/bvh.mjs";
import { retargetClip } from "./motion/retarget.mjs";

const root = dirname(dirname(fileURLToPath(import.meta.url)));
const manifestPath = join(root, "motions", "bandai-namco-motiondataset-1.json");
const manifest = JSON.parse(readFileSync(manifestPath, "utf8"));
const clips = {};

for (const definition of manifest.clips) {
  const sourcePath = join(root, manifest.sourceRoot, definition.source);
  const annotationPath = sourcePath.replace(/\.bvh$/, ".json");
  const annotation = JSON.parse(readFileSync(annotationPath, "utf8"));
  if (annotation.content !== definition.content || annotation.style !== definition.style) {
    throw new Error(`${definition.key}: source annotation does not match the manifest`);
  }
  const bvh = parseBvh(readFileSync(sourcePath, "utf8"), definition.source);
  if (Math.abs(bvh.frameTime - 1 / manifest.sourceFps) > 0.000001) {
    throw new Error(`${definition.key}: expected ${manifest.sourceFps} FPS, found ${1 / bvh.frameTime}`);
  }
  clips[definition.key] = retargetClip(bvh, { ...manifest.defaults, ...definition });
}

const output = `/*
 * Generated by scripts/build-motions.mjs. Do not edit by hand.
 *
 * Adapted from Bandai-Namco-Research-Motiondataset-1 at revision ${manifest.sourceRevision}.
 * Source data: ${manifest.sourceUrl}
 * License: CC BY-NC 4.0; see third_party/bandai-namco-motiondataset-1/LICENSE and NOTICE.md.
 * Changes: selected, trimmed, projected to 2D, retargeted to SVGLab's eleven-bone rig,
 * resampled to 60 Hz, and reduced to sparse linear keyframes.
 */
import type { AnimationClip } from "../types";

export const BANDAI_NAMCO_CLIPS = ${JSON.stringify(clips, null, 2)} as const satisfies Record<string, AnimationClip>;
`;

const outputPath = join(root, manifest.output);
if (process.argv.includes("--check")) {
  const current = readFileSync(outputPath, "utf8");
  if (current !== output) throw new Error(`${manifest.output} is stale; run npm run build:motions`);
} else {
  writeFileSync(outputPath, output);
  console.log(`built ${Object.keys(clips).length} motion clips -> ${manifest.output}`);
}
