import { mkdirSync, writeFileSync } from "node:fs";
import { dirname, isAbsolute, join } from "node:path";
import { fileURLToPath } from "node:url";

import { buildCatalog } from "./motion/catalog.mjs";
import { clipToBvh } from "./motion/bvh-write.mjs";

const root = dirname(dirname(fileURLToPath(import.meta.url)));
const args = process.argv.slice(2);
const outIndex = args.indexOf("--out");
const requestedOut = outIndex < 0 ? join("out", "blender") : args[outIndex + 1];
const outDirectory = isAbsolute(requestedOut) ? requestedOut : join(root, requestedOut);
const requested = args.filter((value, index) => !value.startsWith("--") && index !== outIndex + 1);

const catalog = buildCatalog(root);
const keys = requested.length > 0 ? requested : Object.keys(catalog.clips);
for (const key of keys) {
  if (!(key in catalog.clips)) throw new Error(`unknown clip '${key}'`);
}

mkdirSync(outDirectory, { recursive: true });
for (const key of keys) {
  const clip = catalog.clips[key];
  writeFileSync(join(outDirectory, `${key}.bvh`), clipToBvh(clip, catalog.rig));
  const origin = key in catalog.authored ? `authored, from ${catalog.origins[key] ?? "scratch"}` : "manifest";
  console.log(`${key}.bvh  ${clip.duration + 1} frames @ 60 FPS  ${clip.keyframes.length} shipped keyframes  (${origin})`);
}

writeFileSync(join(outDirectory, "README.md"), `# SVGLab clips for review

Generated by \`npm run export:motions\`. One BVH per clip, baked at one frame per 60 Hz tick
so the file plays exactly what the lab plays.

## Opening one

1. File → Import → Motion Capture (.bvh).
2. Leave scaling at 1. The rig is authored in SVG units, so the fighter is about 110 units tall.
3. Set the scene to **60 FPS** before you export anything back out.

The skeleton is SVGLab's eleven bones in the XY plane, y up. Depth is unused: only rotation
about Z and the root's vertical travel mean anything.

## Sending changes back

Export the edited action as BVH at 60 FPS, then:

\`\`\`bash
npm run import:motions -- <file.bvh> --key <clipKey>
\`\`\`

That writes \`motions/authored/<clipKey>.json\` and prints what moved. Out-of-plane rotation,
depth translation, and horizontal root travel are reported and dropped — the rig has nowhere
to put them. Run \`npm run build:motions\` to fold the result into the catalog.

Nothing in this directory is read by the lab or tracked by git.
`);
console.log(`\nexported ${keys.length} clips -> ${outDirectory.replace(`${root}/`, "")}`);
