import { copyFileSync, mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { dirname, isAbsolute, join } from "node:path";
import { fileURLToPath } from "node:url";

import { boneArtSvg, readBoneArt } from "./motion/art.mjs";
import { buildCatalog } from "./motion/catalog.mjs";
import { clipToBvh } from "./motion/bvh-write.mjs";

const root = dirname(dirname(fileURLToPath(import.meta.url)));
const args = process.argv.slice(2);
const outIndex = args.indexOf("--out");
const requestedOut = outIndex < 0 ? join("out", "blender") : args[outIndex + 1];
const outDirectory = isAbsolute(requestedOut) ? requestedOut : join(root, requestedOut);
const requested = args.filter((value, index) => !value.startsWith("--") && index !== outIndex + 1);

const catalog = buildCatalog(root);
const keys = requested.length > 0 ? requested : Object.keys(catalog.clips);
for (const key of keys) {
  if (!(key in catalog.clips)) throw new Error(`unknown clip '${key}'`);
}

mkdirSync(outDirectory, { recursive: true });
for (const key of keys) {
  const clip = catalog.clips[key];
  writeFileSync(join(outDirectory, `${key}.bvh`), clipToBvh(clip, catalog.rig));
  const origin = key in catalog.authored ? `authored, from ${catalog.origins[key] ?? "scratch"}` : "manifest";
  console.log(`${key}.bvh  ${clip.duration + 1} frames @ 60 FPS  ${clip.keyframes.length} shipped keyframes  (${origin})`);
}

// A BVH carries bones and nothing else, so the artwork goes beside it: one file per bone, in
// that bone's own coordinates, for the setup script to place and parent.
const artDirectory = join(outDirectory, "art");
mkdirSync(artDirectory, { recursive: true });
const art = readBoneArt(
  readFileSync(join(root, "src", "svg", "fighter.svg"), "utf8"),
  readFileSync(join(root, "src", "app", "styles.css"), "utf8"),
);
for (const [bone, elements] of art) {
  writeFileSync(join(artDirectory, `${bone}.svg`), boneArtSvg(bone, elements));
}
copyFileSync(join(root, "scripts", "blender", "setup.py"), join(outDirectory, "setup.py"));

writeFileSync(join(outDirectory, "README.md"), `# SVGLab clips for review

Generated by \`npm run export:motions\`. One BVH per clip, baked at one frame per 60 Hz tick
so the file plays exactly what the lab plays, plus each bone's artwork and a setup script that
puts the two together.

## Opening a clip with the fighter attached

\`\`\`bash
blender --python setup.py -- bnrSwordCutNormal
\`\`\`

Or inside Blender: Scripting tab, open \`setup.py\`, Run. Pass no clip name and it opens the
first one. The script imports the clip, attaches every bone's artwork to its bone, sets the
scene to 60 FPS and the clip's frame range, and points the view at the plane the rig lives in.

A BVH on its own gives you the eleven bones and no character, which is why the script exists.
\`npm run blend:motions\` runs it for every clip and saves a .blend beside each one.

## What you are looking at

The rig is 2D: eleven bones in one plane, authored in SVG units, so the fighter is about 110
units tall and the depth axis carries nothing. Numpad 1 is the view that matters. Only rotation
about the depth axis and the root's vertical travel mean anything on the way back.

## Sending changes back

Export the edited action as BVH at 60 FPS, then:

\`\`\`bash
npm run import:motions -- <file.bvh> --key <clipKey>
\`\`\`

That writes \`motions/authored/<clipKey>.json\` and prints what moved. Out-of-plane rotation,
depth translation, and horizontal root travel are reported and dropped — the rig has nowhere to
put them. Run \`npm run build:motions\` to fold the result into the catalog.

Import at scale 1. A uniform scale is read back out, but the rig's proportions are the contract.

Nothing in this directory is read by the lab or tracked by git.
`);
console.log(`\nexported ${keys.length} clips and ${art.size} bone art files -> ${outDirectory.replace(`${root}/`, "")}`);
